name: '[CI] Lint'

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Biome check
        run: npm run check
      
      - name: Compile TypeScript
        run: npm run compile